from __future__ import annotations

from datetime import datetime, timezone
import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from pydantic import BaseModel, Field

from app.core.database import get_supabase_admin_client
from app.middleware.auth_middleware import require_auth
from app.services.llm.openrouter_client import OpenRouterLLMClient, OPENROUTER_MODELS

router = APIRouter(prefix="/api/v1/chat", tags=["chat"])
logger = logging.getLogger(__name__)


class CreateSessionRequest(BaseModel):
    subject: Optional[str] = None
    mode: Optional[str] = None


class CreateMessageRequest(BaseModel):
    role: str = Field(pattern="^(user|assistant)$")
    content: str = Field(min_length=1)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


async def _generate_and_set_session_title(session_id: str, user_id: str, first_user_message: str) -> None:
    try:
        client = get_supabase_admin_client()
        session_result = client.table("chat_sessions").select("title").eq("id", session_id).eq("user_id", user_id).limit(1).execute()
        current_title = (session_result.data or [{}])[0].get("title")
        if current_title and current_title != "New Conversation":
            return

        prompt = (
            "Generate a short conversation title from this first user message. "
            "Rules: 3-6 words, no quotes, no punctuation at the end, title case, medically relevant if possible.\n\n"
            f"User message: {first_user_message.strip()}"
        )
        system_prompt = "You create concise chat titles. Return only the title text."

        try:
            llm = OpenRouterLLMClient(OPENROUTER_MODELS["fast"])
            generated = (await llm.generate_sync(prompt=prompt, system_prompt=system_prompt)).strip()
            lines = generated.splitlines()
            title = (lines[0].strip() if lines else "")[:80]
        except Exception:
            logger.exception("AI title generation failed, using fallback title")
            title = ""

        if not title:
            title = (first_user_message.strip()[:50] or "New Conversation")

        client.table("chat_sessions").update({"title": title}).eq("id", session_id).eq("user_id", user_id).execute()
    except Exception:
        logger.exception("Failed to set autogenerated session title")


@router.post("/sessions")
def create_session(payload: CreateSessionRequest, user=Depends(require_auth)) -> Dict[str, Any]:
    client = get_supabase_admin_client()
    try:
        result = (
            client.table("chat_sessions")
            .insert(
                {
                    "user_id": user["user_id"],
                    "title": "New Conversation",
                    "subject": payload.subject,
                    "mode": payload.mode,
                }
            )
            .execute()
        )
        if not result.data:
            raise RuntimeError("Session insert returned no data")
        return {"success": True, "data": result.data[0]}
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"error": True, "message": "Failed to create session", "code": "SESSION_CREATE_FAILED", "details": {"reason": str(exc)}}) from exc


@router.get("/sessions")
def get_sessions(user=Depends(require_auth)) -> Dict[str, Any]:
    client = get_supabase_admin_client()
    try:
        sessions_result = (
            client.table("chat_sessions")
            .select("*")
            .eq("user_id", user["user_id"])
            .order("last_message_at", desc=True)
            .execute()
        )
        sessions = sessions_result.data or []

        session_ids = [s["id"] for s in sessions if s.get("id")]
        previews: Dict[str, str] = {}
        if session_ids:
            messages_result = (
                client.table("chat_messages")
                .select("session_id,content,created_at")
                .in_("session_id", session_ids)
                .eq("user_id", user["user_id"])
                .order("created_at", desc=True)
                .execute()
            )
            for msg in messages_result.data or []:
                sid = msg.get("session_id")
                if sid and sid not in previews:
                    previews[sid] = (msg.get("content") or "")[:120]

        enriched = []
        for s in sessions:
            copy = dict(s)
            copy["last_message_preview"] = previews.get(s.get("id"), "")
            enriched.append(copy)
        return {"success": True, "data": enriched}
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"error": True, "message": "Failed to list sessions", "code": "SESSION_LIST_FAILED", "details": {"reason": str(exc)}}) from exc


@router.get("/sessions/{session_id}")
def get_session(session_id: str, user=Depends(require_auth)) -> Dict[str, Any]:
    client = get_supabase_admin_client()
    try:
        session_result = client.table("chat_sessions").select("*").eq("id", session_id).eq("user_id", user["user_id"]).limit(1).execute()
        if not session_result.data:
            raise HTTPException(status_code=404, detail={"error": True, "message": "Session not found", "code": "SESSION_NOT_FOUND"})

        messages_result = (
            client.table("chat_messages")
            .select("*")
            .eq("session_id", session_id)
            .eq("user_id", user["user_id"])
            .order("created_at", desc=False)
            .execute()
        )

        session_data = dict(session_result.data[0])
        session_data["messages"] = messages_result.data or []
        return {"success": True, "data": session_data}
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"error": True, "message": "Failed to fetch session", "code": "SESSION_FETCH_FAILED", "details": {"reason": str(exc)}}) from exc


@router.delete("/sessions/{session_id}")
def delete_session(session_id: str, user=Depends(require_auth)) -> Dict[str, Any]:
    client = get_supabase_admin_client()
    try:
        client.table("chat_messages").delete().eq("session_id", session_id).eq("user_id", user["user_id"]).execute()
        client.table("chat_sessions").delete().eq("id", session_id).eq("user_id", user["user_id"]).execute()
        return {"success": True}
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"error": True, "message": "Failed to delete session", "code": "SESSION_DELETE_FAILED", "details": {"reason": str(exc)}}) from exc


@router.post("/sessions/{session_id}/messages")
def save_message(
    session_id: str,
    payload: CreateMessageRequest,
    background_tasks: BackgroundTasks,
    user=Depends(require_auth),
) -> Dict[str, Any]:
    client = get_supabase_admin_client()
    try:
        insert = (
            client.table("chat_messages")
            .insert(
                {
                    "session_id": session_id,
                    "user_id": user["user_id"],
                    "role": payload.role,
                    "content": payload.content,
                }
            )
            .execute()
        )
        if not insert.data:
            raise RuntimeError("Message insert returned no data")

        now_iso = _now_iso()
        client.table("chat_sessions").update({"last_message_at": now_iso, "updated_at": now_iso}).eq("id", session_id).eq("user_id", user["user_id"]).execute()

        # Non-blocking auto-title generation from first user message
        if payload.role == "user":
            background_tasks.add_task(
                _generate_and_set_session_title,
                session_id,
                user["user_id"],
                payload.content,
            )

        return {"success": True, "data": insert.data[0]}
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"error": True, "message": "Failed to save message", "code": "MESSAGE_CREATE_FAILED", "details": {"reason": str(exc)}}) from exc
