import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}", "./lib/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        surface: "var(--surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-bright": "var(--surface-bright)",
        primary: "var(--primary)",
        "primary-fixed": "var(--primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "primary-container": "var(--primary-container)",
        "on-primary": "var(--on-primary)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "outline-variant": "var(--outline-variant)",
        error: "var(--error)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "aa-bg": "var(--aa-bg)",
        "aa-bg-2": "var(--aa-bg-2)",
        "aa-s1": "var(--aa-s1)",
        "aa-s2": "var(--aa-s2)",
        "aa-s3": "var(--aa-s3)",
        "aa-s4": "var(--aa-s4)",
        "aa-input": "var(--aa-input)",
        "aa-amber": "var(--aa-amber)",
        "aa-amber-lt": "var(--aa-amber-lt)",
        "aa-amber-bg": "var(--aa-amber-bg)",
        "aa-amber-border": "var(--aa-amber-border)",
        "aa-teal": "var(--aa-teal)",
        "aa-teal-lt": "var(--aa-teal-lt)",
        "aa-teal-bg": "var(--aa-teal-bg)",
        "aa-teal-border": "var(--aa-teal-border)",
        "aa-purple": "var(--aa-purple)",
        "aa-purple-bg": "var(--aa-purple-bg)",
        "aa-coral": "var(--aa-coral)",
        "aa-coral-bg": "var(--aa-coral-bg)",
        "aa-coral-border": "var(--aa-coral-border)",
        "aa-caution": "var(--aa-caution)",
        "aa-caution-bg": "var(--aa-caution-bg)",
        "aa-caution-border": "var(--aa-caution-border)",
        "aa-green": "var(--aa-green)",
        "aa-green-bg": "var(--aa-green-bg)",
        "aa-green-border": "var(--aa-green-border)",
        "aa-red": "var(--aa-red)",
        "aa-text-1": "var(--aa-text-1)",
        "aa-text-2": "var(--aa-text-2)",
        "aa-text-3": "var(--aa-text-3)",
        "aa-border": "var(--aa-border)",
        "aa-border2": "var(--aa-border2)",
        almond: {
          background: "#131313",
          surface: "#131313",
          "surface-container-lowest": "#0e0e0e",
          "surface-container-low": "#1c1b1b",
          "surface-container": "#201f1f",
          "surface-container-high": "#2a2a2a",
          "surface-container-highest": "#353534",
          "surface-bright": "#3a3939",
          primary: "#fff2de",
          "primary-fixed": "#f2e0c3",
          "primary-fixed-dim": "#d5c5a8",
          "primary-container": "#e6d5b8",
          "on-primary": "#392f1b",
          "on-surface": "#e5e2e1",
          "on-surface-variant": "#cec5b9",
          "outline-variant": "#4c463d",
          error: "#ffb4ab",
          "error-container": "#93000a",
          "on-error-container": "#ffdad6",
          "tertiary-fixed-dim": "#c4c5d7",
        },
        "almond-bg": "#131313",
        "almond-card": "#1c1b1b",
        "almond-border": "rgba(76,70,61,0.15)",
        "almond-primary": "#fff2de",
        "almond-primary-hover": "#f2e0c3",
        "almond-secondary": "#d5c5a8",
        "almond-success": "#fff2de",
        "almond-error": "#ffb4ab",
        "almond-warning": "#fff2de",
        "almond-info": "#c4c5d7",
        "almond-text": "#e5e2e1",
        "almond-text-secondary": "#cec5b9",
        "almond-text-muted": "rgba(206,197,185,0.6)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        headline: ["Noto Serif", "serif"],
        display: ["Noto Serif", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        card: "0 4px 24px rgba(0,0,0,0.35)",
        glow: "0 0 20px rgba(229,213,184,0.05)",
        focus: "0 0 0 2px rgba(255,242,222,0.4)",
      },
      backgroundImage: {
        "almond-radial": "radial-gradient(circle at center, rgba(230,213,184,0.05) 0%, rgba(19,19,19,0) 70%)",
        "tactile-gradient": "linear-gradient(135deg, #fff2de 0%, #e6d5b8 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
